# **NN** Implementation (Forward + Backward Propagation)
1. Add input in /test/input and model in /test/model with .txt format, makesure they both have the same filename.
2. Input the filename for both the input and the model, ensuring that they have the same filename.
3. Scroll down and click on `./tmp/network.html`. This will redirect you to network.html, which you can then open the visualization using a live server.

#### Made by:
- Samuel Christoper Swandi - 13520075
- Grace Claudia - 13520078
- Ubaidillah Ariq Prathama - 13520085
- Patrick Amadeus Irawan - 13520109

------------

List of Content

1. [Library & Dependencies](#library)
2. [Helper Function](#helper)
3. [Neural Network Visualization](#visualization)

## Library & Dependencies <a name="library"></a>

In [ ]:
!python3 -m pip install pyvis==0.3.2
!python3 -m pip install networkx==2.6.3
!python3 -m pip install numpy==1.21.6

In [1]:
import numpy as np
from pandas import DataFrame
from sklearn.neural_network import MLPClassifier
import os

from pyvis.network import Network

## **Class**

#### Connected Layer

In [2]:
class ConnectedLayer:
    def __init__(self, input_size, output_size, weights):
        self.input_size = input_size
        self.output_size = output_size
        self.weights = weights[1:]
        self.bias = weights[0]

    def forward(self, input):
        self.input = input
        return np.dot(input, self.weights) + self.bias

#### Activation Layer

In [3]:
class ActivationLayer:
    def __init__(self, activation):
        self.activation = activation
    
    def forward(self, input):
        self.input = input
        return self.activation(input)

#### Neural Network

In [526]:
from math import ceil 

class NeuralNetwork:
    def __init__(self):
        self.layers = []

    def add(self, layer):
        self.layers.append(layer)
    
    def predict(self, x):
        complete_result = []
        output = x[:, 1:]

        for layer in self.layers:
            output = layer.forward(output)
            if isinstance(layer, ActivationLayer):
                complete_result.append(output)

        return complete_result[-1] , complete_result
    
    def print_weight(self):
        i = 0
        for layer in self.layers:
            if not isinstance(layer, ActivationLayer):
                print("|____Layer {}___|".format(i))
                print("---B I A S---")
                print(layer.bias)
                print("---N E U R O N S---")
                print(layer.weights)
                i+=1
            print()

    def fit(self, x_train, y_train, learning_rate=0.1, epochs = 5, batch_size = 2, err_threshold = 0.01):
        # batch size validation
        if batch_size > len(x_train) or batch_size <= 0:
            print("Batch size {} invalid.".format(batch_size))
            print("Batch size range [{}...{}]".format(1,len(x_train)))
            return

        print("WEIGHT ORI")
        self.print_weight()
        print("initial error=", sse(predict_output(x_train, self)[0], y_train))
        print("X_train")
        print(x_train)
        print("Pred",predict_output(x_train, self)[0])
        print("Ori", y_train)
        print()
        # training loop
        for i in range(epochs):  # Epoch Loop
            print("- - - - - - - - - - - - - - - - EPOCH {} - - - - - - - - - - - - - - - -".format(i+1))
            # err = 0
            start_i = 0
            end_i = batch_size

            for j in range(ceil(len(x_train) / batch_size)):  # Mini Batch Loop
                print("============BATCH {}==============".format(j + 1))
                batch_x_train = x_train[start_i:end_i]
                batch_y_train = y_train[start_i:end_i]

                # FORWARD PROPAGATION
                batch_y_pred, complete_out = predict_output(batch_x_train, self)
                batch_y_pred = np.array(batch_y_pred)
                # err += sse(batch_y_pred, batch_y_train)

                # BACKWARD PROPAGATION
                out_grad = None
                hid_grad = []

                for k in range(len(batch_x_train)):  # Single Sample Backpropagation Loop
                    sample_y_pred = batch_y_pred[k]
                    sample_y_train = batch_y_train[k]

                    #-------------- Output Gradient --------------#
                    prev_out = uniform2D(np.array(complete_out)[k, -2]).reshape(-1,1)

                    # Duplicate predecessor to match output layer neuron size & append bias
                    succ_size = len(complete_out[0][-1])
                    sample_pred_out = np.hstack([prev_out] * succ_size)
                    sample_pred_out = np.vstack([np.ones(succ_size),sample_pred_out])

                    # print("\n--Output Materials--")
                    # print("sample_y_pred")
                    # print(sample_y_pred)
                    # print("sample_y_train")
                    # print(sample_y_train)
                    # print("sample_pred_out")
                    # print(sample_pred_out)

                    dE_dW, succ_dE_dNet = grad_output(sample_y_pred, sample_y_train, sample_pred_out, 2) # TODO CHANGE NOT SIGMOID
                    if out_grad is None:
                        out_grad = dE_dW
                    else:
                        out_grad += dE_dW

                    
                    # -------------- Hidden Gradient --------------#
                    # TODO : INCREMENTAL LAYER IMPLEMENTATION, STILL IMPLEMENTED DIRECTLY TO INPUT, cant support more than 3 layer
                    prev_out = np.array(batch_x_train[k][1:]).reshape(-1,1)  # cut the bias first
                    # prev_out = uniform2D(np.array(complete_out)[k, -2]).reshape(-1,1)
                    
                    succ_out = np.array(complete_out)[k, -2].reshape(-1,1)
                    succ_weight = np.array(self.layers[-2].weights)
                    # Duplicate predecessor to match succ layer neuron size & append bias
                    succ_size = len(complete_out[0][-2])
                    sample_pred_out = np.hstack([prev_out] * succ_size)
                    sample_pred_out = np.vstack([np.ones(succ_size),sample_pred_out])

                    # print("\n--Hidden Materials--")
                    # print("sample_pred_out")
                    # print(sample_pred_out)
                    # print("succ_out")
                    # print(succ_out)
                    # print("succ_dE_dNet")
                    # print(succ_dE_dNet)
                    # print("succ_weight")
                    # print(succ_weight)

                    dEtotal_dW, succ_dEtotal_dNet = grad_hidden(succ_dE_dNet, succ_weight, succ_out, sample_pred_out, 2) # TODO CHANGE NOT SIGMOID
                    hid_grad.append(dEtotal_dW)


                out_delta = -learning_rate * out_grad
                hid_delta = -learning_rate * np.array(hid_grad)

                # reverse hidden delta
                deltas = (hid_delta[::-1].tolist() + [out_delta.tolist()])
                for d_i in range(len(deltas)):
                    deltas[d_i] = np.array(deltas[d_i])
                # print("---All Delta---")
                # print(deltas)

                # Update weight
                d_i = 0
                for layer in self.layers:
                    if not isinstance(layer, ActivationLayer):
                        layer.bias += deltas[d_i][0]
                        layer.weights += deltas[d_i][1:]
                        d_i+=1  

                # Increment next batch
                start_i += batch_size
                end_i += batch_size
                print()

                self.print_weight()


            # calculate average error on all samples
            print("X_train")
            print(x_train)
            print("Pred")
            print(predict_output(x_train, self)[0])
            print("Ori")
            print(y_train)
            err = sse(predict_output(x_train, self)[0], y_train)

            print("Epoch {}/{}   error={}".format(i+1,epochs, err))
            if err < err_threshold:
                print("Curr error < threshold. Finishing Epoch")
                break
        print("\n----------------------------------------------------------")
        print("============|==========FINAL WEIGHT===========|===========")
        print("----------------------------------------------------------")

        self.print_weight()



In [5]:
def uniform2D(arr):
    return np.array([np.array(i) for i in arr])

## **Helper** Function <a class="anchor" id="helper"></a>

#### Activation Function

In [6]:
def linear(net):
    return net

def ReLU(net):
    return np.maximum(0,net)

def sigmoid(net):
    return 1/(1+np.exp(-net))

def softmax(net):
    res = []
    for sample in net:
        res.append(np.exp(sample)/np.sum(np.exp(sample)))
    return np.array(res)

#### Loss Function

In [7]:
def mse(y_true, y_pred):
    return np.mean(np.square(y_true - y_pred))

def sse(y_true, y_pred):
    return np.sum(np.square(y_true - y_pred))

#### Model Loading Function

In [8]:
def model_load(data):
    '''
    Function to load model from file
    INPUT :     data -> data from model file

    OUTPUT :    weights -> weights of each model neuron
                list_prev_size -> list of previous layer size
                list_layer_size -> list of current layer size
                list_activation -> list of activation function
    '''

    idx = 1
    weights,list_prev_size,list_layer_size,list_activation = [],[],[],[]

    for i in range(int(data[0]) - 1):
        # Loading size & act function
        prev_size, layer_size, activation = [int(i) for i in data[idx].split()]
        list_prev_size.append(prev_size)
        list_layer_size.append(layer_size)
        list_activation.append(activation)
        
        # Loading weights
        idx += 1
        weight = []
        for j in range(prev_size + 1):
            weight.append([float(i) for i in data[idx].split()])
            idx += 1
        weights.append(weight)
    
    # Verbose Information
    print('---Model Information---')
    print('Number of layers :', len(list_prev_size) + 1)
    print('Input size :', list_prev_size[0])
    print('Output size :', list_layer_size[-1])

    print()
    print('Weights :', weights)
    print('Previous layer size :', list_prev_size)
    print('Current layer size :', list_layer_size)
    print('Activation function :', list_activation)

    return weights, list_prev_size, list_layer_size, list_activation

#### Input Loading Function

In [9]:
def generate_x_train(input_data):
    x_train = []
    # Parse each line
    for i in range(len(input_data)):
        x_train.append([float(i) for i in input_data[i].split()])

    return np.array(x_train)

#### Predict Output Function

In [10]:
def predict_output(x, net):
    '''
    Function to predict output from input data
    INPUT :     x-> input data
                net -> NeuralNetwork object

    OUTPUT :    out -> output of the model
                complete_out -> complete output of the model, visualization purpose
    '''
    # Predict output
    out, complete_out = net.predict(x)

    # Gather complete output
    n_complete_out = []
    for i in range(len(complete_out[0])):
        n_complete_out.append([complete_out[0][i], complete_out[-1][i]])

    complete_out = n_complete_out
    return out, complete_out

#### SSE Errors Function + microhelper

In [11]:
def compute_out_and_errors(output_data, out):
    '''
    Function to calculate output error
    INPUT :     output_data -> output data from output file
                out -> output of the model, obtained from predict_output function

    OUTPUT :    out_pred -> output of the model (flattened)
                out_true -> output from output_data (flattened)
                sse_error -> sum squared error
                sse_error <= max_sse -> boolean value, True if sse_error <= max_sse, False otherwise
    '''
    # Assign y_train from output_data
    parsed_output = [[float(j) for j in i.split()] for i in output_data]
    out_pred = out.flatten()
    out_true = np.array(parsed_output[:-1]).flatten()
    max_sse = parsed_output[-1][0]

    return out_pred, out_true, sse(out_true, out_pred), sse(out_true, out_pred) <= max_sse

## **Load** Section

Entrypoint

In [473]:
MODEL_FOLDER = '../test/model/'
INPUT_FOLDER = '../test/input/'
OUTPUT_FOLDER = '../test/output/'
# read file from test folder
def read_file(folder_path, file_name):
    with open(folder_path + file_name, 'r') as file:
        data = [i.rstrip("\n") for i in file.readlines()]
    return data

filename = input('Enter test case name (with extension): ')
data = read_file(MODEL_FOLDER, filename)
input_data = read_file(INPUT_FOLDER, filename)

try: 
    output_data = read_file(OUTPUT_FOLDER, filename)
except:
    output_data = None

model_load

In [474]:
weights, list_prev_size, list_layer_size, list_activation = model_load(data)

---Model Information---
Number of layers : 3
Input size : 2
Output size : 1

Weights : [[[0.25, 0.25], [0.25, 0.25], [0.25, 0.25]], [[0.0], [0.25], [0.25]]]
Previous layer size : [2, 2]
Current layer size : [2, 1]
Activation function : [2, 2]


Build NN

In [475]:
# Build NN model
act = {0: linear, 1: ReLU, 2: sigmoid, 3: softmax}
net = NeuralNetwork()
for i in range (int(data[0]) - 1):
    net.add(ConnectedLayer(list_prev_size[i], list_layer_size[i], weights[i]))
    net.add(ActivationLayer(act[list_activation[i]]))

## **Predict** Section

Prepare x_train & predict output

In [476]:
x_train = generate_x_train(input_data)
out, complete_out = predict_output(x_train, net)

# Print the information, complete with brief verbose
print('---Prediction Information---')
print('Input data :', x_train)
print('Output data :', out)

---Prediction Information---
Input data : [[ 1.  1.  1.]
 [ 1.  1. -1.]
 [ 1. -1.  1.]
 [ 1. -1. -1.]]
Output data : [[0.58409077]
 [0.569813  ]
 [0.569813  ]
 [0.55451042]]


## Compute Error with **Sum Squared Error (SSE)**

Sum Squared Error (SSE) is a mathematical function used in statistics and machine learning to measure the difference between predicted and actual values. It is commonly used as a cost function in various optimization algorithms, such as gradient descent.

The SSE is calculated by taking the difference between each predicted value and its corresponding actual value, squaring the difference, and then summing all of the squared differences:

$$SSE = \sum_{i=1}^{n}(y_i - \hat{y}_i)^2$$

Where:
- $n$ is the number of data points
- $y_i$ is the actual value of the i-th data point
- $\hat{y}_i$ is the predicted value of the i-th data point

The SSE gives an indication of how well the model fits the data. A lower SSE indicates that the model is a better fit for the data.

In machine learning, the SSE is often used as a cost function to be minimized during training of a model. The goal is to find the set of model parameters that minimizes the SSE, thus improving the accuracy of the model's predictions.

In [477]:
out_pred, out_true, sse_err, isLessThanMaxSSE = compute_out_and_errors(output_data, out)

print('Output prediction :', out_pred)
print('Output true :', out_true)
print('SSE  : ', sse_err)
print("sse <= max_sse  :", isLessThanMaxSSE)

Output prediction : [0.58409077 0.569813   0.569813   0.55451042]
Output true : [ 1. -1. -1.  1.]
SSE  :  5.300067181259587
sse <= max_sse  : False


## Neural Network Visualization with **Pyvis**

Pyvis is a Python library that provides an easy-to-use interface for visualizing complex networks, including neural networks. Implementation of the visualization is enlisted below:

In [441]:
def visualize_network(data, complete_out) -> Network:
    n = int(data[0])

    # Constant
    XSTEP, YSTEP, SIZE = 300, 300, 10

    # Nodes
    nodes = []
    node_i = 1

    # Nodes Value
    value = []
    x_val = 0
    y_val = 0

    # Position
    x = []
    y = []

    # Styling + Text
    label = []
    color = []
    edge = []
    title = []

    # Indexing
    src_idx = 0
    idx = 1

    for i_layer in range(n - 1):
        n_curr, n_next, _ = [int(i) for i in data[idx].split()]

        if i_layer == 0:  # means that this is the first layer, hence construct input
            for i_node in range(n_curr + 1):
                if i_node == 0:  # bias
                    color.append("#dd4b39")
                    label.append("Input[bias]")
                    temp = ""
                    for i in range (len(input_data)):
                        temp += str(x_train[i][0])
                        if i < len(input_data) - 1:
                            temp += ", "
                    title.append(temp)
                else:
                    color.append("#162347")
                    label.append("Input[{}]".format(i_node))
                    temp = ""
                    for i in range (len(input_data)):
                        temp += str(x_train[i][i_node])
                        if i < len(input_data) - 1:
                            temp += ", "
                    title.append(temp)
                value.append(SIZE)
                x.append(x_val)
                y.append(y_val)
                y_val += YSTEP
                nodes.append(node_i)
                node_i += 1
            x_val += XSTEP

        y_val = 0
        # always construct the next layer
        for i_node in range(n_next + 1):
            if i_node == 0:
                if i_layer == n - 2:
                    continue
                color.append("#dd4b39")
                label.append("HL{}[bias]".format(i_layer + 1))
                temp = ""
                for i in range (len(input_data)):
                    temp +=  "1"
                    if i < len(input_data) - 1:
                        temp += ", "
                title.append(temp)
            else:
                color.append("#162347")
                if i_layer == n - 2:
                    label.append("Output[{}]".format(i_node))
                else:
                    label.append("HL{}[{}]".format(i_layer + 1, i_node))
                temp = ""
                for i in range (len(input_data)):
                    temp += str(complete_out[i][i_layer][i_node - 1])
                    if i < len(input_data) - 1:
                        temp += ", "
                title.append(temp)
            value.append(SIZE)
            x.append(x_val)
            y.append(y_val)
            y_val += YSTEP
            nodes.append(node_i)
            node_i += 1
        x_val += XSTEP

        idx += 1
        for origin in range(n_curr + 1):
            dst_idx = -1
            for w in reversed(data[idx].split()):
                edge.append((nodes[src_idx], nodes[dst_idx], w))
                dst_idx -= 1
            src_idx += 1
            idx += 1

    g = Network(notebook=True, cdn_resources="remote")
    g.add_nodes(nodes,title = title,value = value,x=x,y=y,label = label,color = color)

    for e in edge:
        g.add_edge(e[0], e[1], title = e[2], color="#162347")

    for n in g.nodes:
        n.update({'physics': False})
    
    return g

Visualize using Helper Function

In [ ]:
g = visualize_network(data, complete_out)
g.show("./tmp/network.html")

## Backpropagation Section

Fit and Train NN

In [529]:
# Build NN model
act = {0: linear, 1: ReLU, 2: sigmoid, 3: softmax}
net = NeuralNetwork()
for i in range (int(data[0]) - 1):
    net.add(ConnectedLayer(list_prev_size[i], list_layer_size[i], weights[i]))
    net.add(ActivationLayer(act[list_activation[i]]))

# Train NN
x_train = x_train
y_train = out_true.reshape(len(x_train), list_layer_size[-1])

net.fit(x_train, y_train, learning_rate=0.1, epochs=5, batch_size=4)

WEIGHT ORI
|____Layer 0___|
---B I A S---
[0.25, 0.25]
---N E U R O N S---
[[0.25, 0.25], [0.25, 0.25]]


|____Layer 1___|
---B I A S---
[0.0]
---N E U R O N S---
[[0.25], [0.25]]


initial error= 5.300067181259587
X_train
[[ 1.  1.  1.]
 [ 1.  1. -1.]
 [ 1. -1.  1.]
 [ 1. -1. -1.]]
Pred [[0.58409077]
 [0.569813  ]
 [0.569813  ]
 [0.55451042]]
Ori [[ 1.]
 [-1.]
 [-1.]
 [ 1.]]

- - - - - - - - - - - - - - - - EPOCH 1 - - - - - - - - - - - - - - - -
============BATCH 1==============

|____Layer 0___|
---B I A S---
[0.25067717 0.25067717]
---N E U R O N S---
[[0.24932283 0.24932283]
 [0.24932283 0.24932283]]


|____Layer 1___|
---B I A S---
[-0.00236782 -0.00236782]
---N E U R O N S---
[[0.25236782 0.25236782]
 [0.24763218 0.24763218]]


X_train
[[ 1.  1.  1.]
 [ 1.  1. -1.]
 [ 1. -1.  1.]
 [ 1. -1. -1.]]
Pred
[[0.58349751 0.58349751]
 [0.56925293 0.56925293]
 [0.56925293 0.56925293]
 [0.55398721 0.55398721]]
Ori
[[ 1.]
 [-1.]
 [-1.]
 [ 1.]]
Epoch 1/5   error=10.595022445451665
- - - - - 

C:\Users\HP\AppData\Local\Temp/ipykernel_39484/4256562812.py:74: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  prev_out = uniform2D(np.array(complete_out)[k, -2]).reshape(-1,1)
C:\Users\HP\AppData\Local\Temp/ipykernel_39484/4256562812.py:101: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  succ_out = np.array(complete_out)[k, -2].reshape(-1,1)


In [320]:
def grad_output(sample_y_pred, sample_y_train, sample_pred_out, act_type):
    if act_type == 0: #linear
        dO_dNet = 1
    elif act_type == 1: #relu
        dO_dNet = np.where(sample_y_pred < 0, 0, 1)
    elif act_type == 2: #sigmoid
        dO_dNet = sample_y_pred * (1 - sample_y_pred)
    
    # TODO SOFTMAX
    
    dE_dO = -(sample_y_train - sample_y_pred)
    dNet_dW = sample_pred_out                    
    dE_dW = dE_dO * dO_dNet * dNet_dW
    # print("\n--Calculation---")
    # print("dE_dO")
    # print(dE_dO)
    # print("dO_dNet")
    # print(dO_dNet)
    # print("dNet_dW")
    # print(dNet_dW)
    # print("dE_dW")
    # print(dE_dW)

    return dE_dW, dE_dO * dO_dNet

In [322]:
def grad_hidden(succ_dE_dNet, succ_weight, succ_out, sample_pred_out, act_type):
    if act_type == 0: #linear
        dO_dNet = 1
    elif act_type == 1: #relu
        dO_dNet = np.where(sample_y_pred < 0, 0, 1)
    elif act_type == 2: #sigmoid
        dH_dNet = (succ_out * (1 - succ_out)).flatten()
    
    # TODO: SOFTMAX

    dE_dNet = succ_dE_dNet
    dNet_dH = succ_weight
    dEtotal_dH = np.sum(dE_dNet * dNet_dH, axis = 1)
    dNet_dW = sample_pred_out
    dEtotal_dNet = dEtotal_dH * dH_dNet
    dEtotal_dW = dEtotal_dNet * dNet_dW

    # print("dEtotal_dH")
    # print(dEtotal_dH)
    # print("dH_dNet")
    # print(dH_dNet)
    # print("dNet_dW")
    # print(dNet_dW)
    # print("dEtotal_dNet")
    # print(dEtotal_dNet)
    # print("dEtotal_dW")
    # print(dEtotal_dW)

    return dEtotal_dW, dEtotal_dNet

In [433]:
l = [[2,3,4],[23],[3,4,5]]
for i in range(len(l)):
    l[i] = np.array(l[i])

print(l)

[array([2, 3, 4]), array([23]), array([3, 4, 5])]
